ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'
urlpatterns = [
    path('i/<slug:slug>/', IdeaDetail.as_view(), name='detail'),
    path('i/<slug:slug>/edit/', IdeaUpdate.as_view(), name='update'),
    path('ideas/', IdeaList.as_view(), name='list'),
    path('submit/', IdeaCreate.as_view(), name='create'),
]

ideator/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import Landing

urlpatterns = [
    path('@/', admin.site.urls),
    path('', include('ideas.urls')),
    path('', Landing.as_view(), name='landing'),
]

ideas/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify

class Idea(models.Model):
    class Meta:
        ordering = ('-created_at',)
    
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(unique=True, max_length=200)
    description = models.TextField(null=True, blank=True)
    external_link = models.URLField(null=True, blank=True)
    internal_link = models.URLField(null=True, blank=True)
    submitted_by = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True)
    color = models.CharField(max_length=20, null=True, blank=True)
    magnitude = models.IntegerField(default=1)
    slug = models.SlugField(unique=True, editable=False)
    session_key = models.TextField(null=True, blank=True)


    def __str__(self):
        return self.title
    
    def save(self, *args, keep_slug=False, **kwargs):
        if not keep_slug: 
            self.slug = slugify(self.title)
        self.validate_unique()
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self, *args, **kwargs):
        return reverse('ideas:detail', kwargs={'slug': self.slug})

ideas/forms.py
from django.forms import ModelForm
from .models import Idea


class IdeaInlineForm(ModelForm):
    class Meta:
        model = Idea
        fields = ['title']

class IdeaForm(ModelForm):
    class Meta:
        model = Idea
        fields = ['title', 'description']
        

ideas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import *
from .forms import IdeaForm



class IdeaList(ListView):
    model = Idea
    context_object_name = 'ideas'
    template_name = 'ideas/list.html'



class IdeaDetail(DetailView):
    model = Idea
    lookup_field = 'slug'
    context_object_name = 'idea'
    template_name = 'ideas/detail.html'

    def get_context_data(self, *args, **kwargs):
        if not self.request.session.session_key: 
            self.request.session.save()
        ctx = super().get_context_data(*args, **kwargs)
        ctx['authorized'] = (self.request.session.session_key == self.object.session_key)
        return ctx


class IdeaCreate(CreateView):
    model = Idea
    form_class = IdeaForm
    template_name = 'ideas/create.html'

    def form_valid(self, form):
        if not self.request.session.session_key: 
            self.request.session.save()
        form.instance.session_key = self.request.session.session_key
        return super().form_valid(form)


class IdeaUpdate(UpdateView):
    model = Idea
    form_class = IdeaForm
    template_name = 'ideas/create.html'


    def form_valid(self, form):
        if not self.request.session.session_key: 
            self.request.session.save()
        if not (self.request.session.session_key == self.object.session_key) and not bool(self.request.session.session_key):
            return HttpResponse(status=403)

        form.instance.session_key = self.request.session.session_key
        return super().form_valid(form)

ideator/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.views.generic import View
from ideas.forms import IdeaInlineForm


class Landing(View):
    def get(self, request):
        return render(request, 'landing.html', {'form': IdeaInlineForm()})

    def post(self, request):
        form = IdeaInlineForm(request.POST)
        if not form.is_valid():
            return HttpResponse(form.errors, status=400)
        idea = form.save(commit=False)
        idea.session_key = request.session.session_key
        idea.save()
        return HttpResponseRedirect(redirect_to=reverse('ideas:detail', kwargs={'slug': idea.slug}))

ideas/templates/ideas/create.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block body %}
<div class="ui inverted vertical masthead center aligned segment">

    <div class="ui text container">
        <h1 class="ui inverted header">
            <strong>Your million dollar idea</strong>
        </h1>
        <div class="ui center aligned basic segment">
            <form action="" method="POST" id="idea-form">
                {% csrf_token %}
                <div class="ui huge input">
                    {% firstof placeholder 'Your million dollar idea' as ph %}
                    {% render_field form.title placeholder=ph %}
                </div>
                <div class="ui horizontal inverted divider">
                    optional description
                </div>
                <div class="ui form input">
                    {% firstof placeholder 'With extra sauce, please' as ph %}
                    {% render_field form.description placeholder=ph rows=4 %}
                </div>
                <br>
                <div style="margin-top:1em;" class="ui form input">
                    <button type="submit" class="ui huge teal inverted button">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ideas/templates/ideas/detail.html
{% extends 'base.html' %}

{% block body %}

<style type="text/css">
    body {
        background-color: #FFFFFF;
        padding-top: 4em;
    }

    .main.container {
        margin-top: 2em;
    }

    .main.menu {
        margin-top: 4em;
        border-radius: 0;
        border: none;
        box-shadow: none;
        transition:
            box-shadow 0.5s ease,
            padding 0.5s ease;
    }

    .main.menu .item img.logo {
        margin-right: 1.5em;
    }

    .overlay {
        float: left;
        margin: 0em 3em 1em 0em;
    }

    .overlay .menu {
        position: relative;
        left: 0;
        transition: left 0.5s ease;
    }

    .main.menu.fixed {
        background-color: #FFFFFF;
        border: 1px solid #DDD;
        box-shadow: 0px 3px 5px rgba(0, 0, 0, 0.2);
    }

    .overlay.fixed .menu {
        left: 800px;
    }

    .text.container .left.floated.image {
        margin: 2em 2em 2em -4em;
    }

    .text.container .right.floated.image {
        margin: 2em -4em 2em 2em;
    }

    .ui.footer.segment {
        margin: 5em 0em 0em;
        padding: 5em 0em;
    }
</style>

<div class="ui main text container">
    {% if authorized %}<a href="{% url 'ideas:update' slug=idea.slug %}"><i class="icon edit"></i>Edit</a>{% endif %}
    <h1 class="ui header">{{ idea.title|title }}</h1>
</div>
<br><br>
<div class="ui text container">
    {% if idea.description %}
    <p>{{ idea.description }}</p>
    {% elif authorized %}
    <p style="color: gray">Click on "Edit" to update or add details to this idea.</p>
    {% endif %}
</div>

{% endblock %}

ideas/templates/ideas/list.html
{% extends 'base.html' %}

{% block body %}


<div style="margin: 3em;" class="ui main text container ">
    <h1 class="ui header">Latest ideas</h1>
    <div class="ui cards">
        {% for idea in ideas %}
        <div class="ui card">
            <div class="content">
              <div class="header">{{ idea.title|title }}</div>
              
              {% if idea.description %}
              <div class="description">{{ idea.description|truncatechars:100 }}</div>
              {% endif %}
            </div>
            <div class="extra content">
              <a class="created">Cool +1</a>
              <a href="{% url 'ideas:detail' slug=idea.slug %}" class="right floated created">View details</a>
            </div>
          </div>
          {% endfor %}
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ doc.title|default:'Titleless' }} • Ideator</title>

    <link rel="stylesheet" href="{% static 'semantic/semantic.css' %}">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    {% block css %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>

    <script defer src="{% static 'semantic/semantic.js' %}"></script>
    {% block js %}{% endblock %}
</head>

<body>

    <!-- Sidebar Menu -->
    <div class="ui vertical inverted sidebar menu">
        <a href="{% url 'landing' %}" class="{% if active == 'home' %}active {% endif %}item">Home</a>
        <a href="{% url 'ideas:list' %}" class="{% if active == 'ideas' %}active {% endif %}item">Ideas</a>
        <a href="{% url 'landing' %}#about" class="{% if active == 'about' %}active {% endif %}item">About</a>
        <a href="#contact" class="{% if active == 'contact' %}active {% endif %}item">Contact</a>
        <a href="{% url 'ideas:create' %}" class="item">Submit your idea <i class="arrow right icon"></i></a>
    </div>
    <div class="pusher">
        {% block navbar %}
        <div class="ui inverted vertical center aligned segment">
            <div class="ui container">
                <div class="ui large secondary inverted pointing menu">
                    <a class="toc item">
                        <i class="sidebar icon"></i>
                    </a>
                    <a href="{% url 'landing' %}" class="{% if active == 'home' %}active {% endif %}item">Home</a>
                    <a href="{% url 'ideas:list' %}"
                        class="{% if active == 'ideas' %}active {% endif %}item">Ideas</a>
                    <a class="{% if active == 'about' %}active {% endif %}item">About</a>
                    <a class="{% if active == 'contact' %}active {% endif %}item">Contact</a>
                </div>
            </div>
        </div>
        {% endblock %}
        {% block body %}{% endblock %}
        <div class="ui inverted vertical footer segment">
            <div class="ui container">
                <div class="ui stackable inverted divided grid">
                    <div class="six wide column">
                        <h4 class="ui inverted header">Quick Links</h4>
                        <div class="ui inverted link list">
                            <a href="{% url 'landing' %}" class="item">Home</a>
                            <a href="{% url 'ideas:list' %}" class="item">Ideas</a>
                            <a href="{% url 'landing' %}#about" class="item">About</a>
                            <a href="{% url 'ideas:create' %}" class="item">Submit your idea <i class="right arrow icon"></i></a>
                        </div>
                    </div>
                    <div id="contact" class="six wide column">
                        <h4 class="ui inverted header">Ömer Selçuk</h4>
                        <p>This web application is done in my free time.</p>
                        <a href="https://t.me/divisia/"><i class="icon telegram"></i></a>
                        <a href="mailto:omrfyyz@gmail.com"><i class="icon mail"></i></a>
                    </div>
                </div>
                <div class="ui inverted section divider"></div>
                <img src="" class="ui centered mini image">
                <div class="ui horizontal inverted small divided link list">
                    <a class="item" href="#contact">Contact</a>
                    <a class="item" href="#0">Terms and Conditions</a>
                    <a class="item" href="#0">Privacy Policy</a>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document)
            .ready(function () {

                // fix menu when passed
                $('.masthead')
                    .visibility({
                        once: false,
                        onBottomPassed: function () {
                            $('.fixed.menu').transition('fade in');
                        },
                        onBottomPassedReverse: function () {
                            $('.fixed.menu').transition('fade out');
                        }
                    });

                // create sidebar and attach to menu open
                $('.ui.sidebar')
                    .sidebar('attach events', '.toc.item');

            });
    </script>
</body>

</html>

templates/landing.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block js %}
<script defer src="{% static 'js/landing.js' %}"></script>
{% endblock %}
{% block navbar %}
<!-- overwrite -->{% endblock %}
{% block body %}

<!-- Page Contents -->
<div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
        <div class="ui large secondary inverted pointing menu">
            <a class="toc item">
                <i class="sidebar icon"></i>
            </a>
            <a href="{% url 'landing' %}" class="active item">Home</a>
            <a href="{% url 'ideas:list' %}" class="item">Ideas</a>
            <a href="#about" class="item">About</a>
            <a href="#contact" class="item">Contact</a>
        </div>
    </div>

    <div class="ui text container">
        <h1 class="ui inverted header">
            <strong>Ideator 3000</strong>
        </h1>
        <div class="ui center aligned basic segment">
            <form action="" method="POST" id="idea-form">
                {% csrf_token %}
                <div id="message" style="display:none;" class="ui message">
                    <i class="close icon"></i>
                    <div class="header">
                        That idea already exists!
                    </div>
                    <p>It's interesting that you thought it too, though.</p>
                </div>
                <div id="idea-submit" class="ui fluid large action input">
                    {% firstof placeholder 'Your million dollar idea' as ph %}
                    {% render_field form.title placeholder=ph %}
                    <button class="ui inverted white submit button">Submit</button>
                </div>
            </form>
            <div class="ui horizontal inverted divider">
                Or
            </div>
            <a href="{% url 'ideas:list' %}" class="ui large teal labeled icon button">
                Browse others' ideas
                <i class="search icon"></i>
            </a>
        </div>
    </div>
</div>

<div id="about" class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
        <div class="row">
            <div class="eight wide column">
                <h3 class="ui header">Ever run out ideas?</h3>
                <p>We can give your company superpowers to do things that they never thought possible. Let us
                    delight your customers and empower your needs...through pure data analytics.</p>
                <h3 class="ui header">We Make Bananas That Can Dance</h3>
                <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="center aligned column">
                <a class="ui huge button">Check Them Out</a>
            </div>
        </div>
    </div>
</div>


<div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
        <div class="center aligned row">
            <div class="column">
                <h3>"What a Company"</h3>
                <p>That is what they all say about us</p>
            </div>
            <div class="column">
                <h3>"I shouldn't have gone with their competitor."</h3>
                <p>
                    <b>Nan</b> Chief Fun Officer Acme Toys
                </p>
            </div>
        </div>
    </div>
</div>

<div class="ui vertical stripe segment">
    <div class="ui text container">
        <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
        <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing
            nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic
            and worth your attention.</p>
        <a class="ui large button">Read More</a>
        <h4 class="ui horizontal header divider">
            <a href="#">Case Studies</a>
        </h4>
        <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
        <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really
            true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
        <a class="ui large button">I'm Still Quite Interested</a>
    </div>
</div>

{% endblock %}